// let b = 5;

try {
  let a = 2 + b;
} catch (error) {
  console.error(error);
}

console.log("Teste");
